### ISSUE TITLE
Problems in Chromium possibly.

### ISSUE THREAD

**Issue by jenksed** [antimatter15/surplus#1]
I'm running Ubuntu and Surplus works great as far as being able to access my notification window from the toolbar however it is not display the number of new notifications as they come in. It a static grey box at all times. I need this extension BAD! Please help!

**Comment by antimatter15** [comment]
What version of ubuntu and what of chrome?

**Comment by jenksed** [comment]
10.04 LTS and Chrome 12.0.742.112

**Comment by antimatter15** [comment]
Does 2.2 still have the problem?

**Comment by jenksed** [comment]
It seems to be working well. Thank you for addressing the issue so fast. If you ever need me to test my setup on this or any other projects just float me an email. 

Josh Jenks
joshuadavidjenks@gmail.com
