### ISSUE TITLE
for right column add:

### ISSUE THREAD

**Issue by leonzinger** [antimatter15/surplus#11]
position: fixed; 
width: 180px;

so it will behave just like the left one. :)

**Comment by antimatter15** [comment]
What right column?

**Comment by leonzinger** [comment]
The one that contains the "in your circles/"Suggestions/Hangouts/Go Mobile/Send invites" and has the class="a-kh-Ae"

**Comment by antimatter15** [comment]
Surplus doesn't modify the Google+ layout and it's not a feature that I plan on adding.
