### ISSUE TITLE
Surplus Lite enables itself in Linux Chrome 14.0.835.15 dev

### ISSUE THREAD

**Issue by yelvington** [antimatter15/surplus#13]
"A bug affecting Chrome 13 on Windows prevents Surplus from fully working. Because of this, Surplus Lite has been automatically enabled and some features may not be availiable"

However, I'm running 14.0.835.15 dev on Ubuntu Linux.

**Comment by cerebro84** [comment]
Same problem on Google Chome 15.0.849.0 dev-m for Windows.

**Comment by Stubbs** [comment]
and Chrome 12 on OSX.

Can I get you any more info that might help?

**Comment by BillyGalbreath** [comment]
This indeed is a problem for me. I'm not even running Windows OR Chrome 13, and yet this "bug" is affecting me.

Suggestion: Only disabled that specific version on that specific OS.

I'm running Chrome 14.0.835.94 beta on Debian GNU/Linux Sid/Unstable...

**Comment by emperorcezar** [comment]
Same with Chrome 13 on OSX

**Comment by q00u** [comment]
Same with Chrome 14 on OSX
