### ISSUE TITLE
Notification icon renders un(defined)

### ISSUE THREAD

**Issue by redhead** [antimatter15/surplus#16]
My notification icon started recently showing what I believe is letters "un" (as undefined maybe?) instead of number of notifications.
The letters are on the red background but there are no pending notifications on google+ site.

I tried to deactivate and even reinstall plugin, but it was no use.

**Comment by antimatter15** [comment]
shoudl be fixed in 4.0.5

**Comment by redhead** [comment]
It works again, thanks.
