### ISSUE TITLE
Enabling notifications auto-reads everything

### ISSUE THREAD

**Issue by ConstantineXVI** [antimatter15/surplus#3]
Noticed if I turn notifications on; surplus will mark as read when throwing up a notification. Means no shiny red box, and no mobile notifications if I left my computer on by mistake.

**Comment by antimatter15** [comment]
It's an interesting problem to try solving. I tried it at one point.

 I think I discovered that XHR requests don't seem to fire the window.onbeforeload event, so I can't cancel that. 

The other way might be to take the XHR objects early on and replace them with some hacked custom made function.

Maybe it'll be possible when the webRequests API gets stabilized in the future

**Comment by antimatter15** [comment]
mostly fixed in 3.1.41
