### ISSUE TITLE
non-functional in canary

### ISSUE THREAD

**Issue by ttilley** [antimatter15/surplus#4]
The extension appears to be non-functional in google chrome canary build 14.0.813.0. It's just as likely a canary bug as a surplus bug, but I figured I'd throw that out there just in case. Despite being logged in to plus, I see the "ZOMG FIX IT" double-bang in the icon. I AM logged into multiple google accounts, but the error is about the correct account. Just to be safe I attempted multiple values for the active user number.

**Comment by sfarbota** [comment]
Same issue.  When I open the box it either tells me I'm not logged in (even when I am) or shows a section of the Google Images home page.  I am only using it for one Google+ account.

**Comment by sfarbota** [comment]
Also this is in Chromium for me, not Canary.  I am currently running 14.0.814.0 dev-m .
