### ISSUE TITLE
Surplus Settings... what it means?

### ISSUE THREAD

**Issue by equiman** [antimatter15/surplus#6]
Congratulations and thanks for this great Extension :D

Now... my recommendation: In the Surplus Settings you have an options, but there are options that don't understand like: "Use alternate frame host"

Maybe you can add a <div> with a little explanation when the mouse is over an option.

The other is an Issue. I check the option "Check to enable desktop notification sounds" and close the tab, but when I reload the Surplus Settings this option is unchecked.

DP: Sorry my english isn't very good.

**Comment by antimatter15** [comment]
The desktop notification sounds setting is a known bug and will be fixed in
a later version.

**Comment by equiman** [comment]
Excelent. What about the tool tip explanation?
