### ISSUE TITLE
How Do you Tab Between Accounts????

### ISSUE THREAD

**Issue by Isthmus** [antimatter15/surplus#7]
I worte antimatter asking how does one tab between accounts, but the answer I got was that it is in the Options?  OK, I wouldn't have asked had I not already been in the options.  The only thing there that even remotely alludes to other google accounts is the following option:

"Authenticated User (for multiple simulatenous account logins. If you are unsure, just select 0.)"

The problem is that outside of choosing a number (which I assume the number chosen corresponds to the number of Google accounts you have), there is nothing.  no explanation regarding what you are doing and definitely no explanation on how to use Surplus to tab between Google+ accounts.

Any chance you could explain how to use Surplus to tab between different Google+ accounts and how exactly to set this up in Surplus?  I'd appreciate it if you could be specific.

Thanks

**Comment by antimatter15** [comment]
Surplus 3.1.41 should improve the wording of the user switch feature.
